### ISSUE TITLE
Allow configuring enable-underscores-in-headers for nginx ingress in values.yaml

### ISSUE THREAD

**Issue by scsmithr** [cdr/enterprise-helm#4]
The nginx ingress that we ship with will by default drop headers that contain underscores. This can be undesirable when using the devurls feature.

A workaround for the time being is to pull down the chart, and modify https://github.com/cdr/enterprise-helm/blob/master/templates/ingress.yaml#L26 to include `enable-underscores-in-headers: "true"`, and then helm upgrade with the modified chart. The end result should look like: 
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  enable-underscores-in-headers: "true"
  proxy-set-headers: "{{ .Release.Namespace }}/custom-headers"
```
